site :opscode

cookbook "runit", ">= 1.1.2"  # HACK: force-use this version
cookbook "databox"
cookbook "rackbox"

cookbook "application"
cookbook "haproxy"
cookbook "needed_packages", path: './needed_packages'
